{
  "title": "Chị em tier 1",
  "description": "Sống chung dưới một mái nhà với 4 chị em mà tài năng lẫn sự dễ thương của ai cũng thuộc hàng《Siêu thượng cấp》!!\nKiminaga Shikimi là một học sinh nghèo bị phát hiện đang làm thêm, vốn trái với nội quy của nhà trường. Vì tránh bị đuổi, cậu đã nhận lời làm thay việc nhà tại nhà của hiệu trưởng!\nTại mái nhà Kichijouji đó, cả bốn chị em ai cũng có tài năng cùng sắc đẹp khiến cho ai cũng phải ngưỡng mộ!\nHọa sĩ Vtuber・Trưởng nữ Kikuri. Streamer・Thứ nữ Ranka. Pro Gamer・Tam nữ Rume. Seiyuu thiên tài・Tứ nữ Chinana.\nNhưng đổi lấy tài năng ấy, họ lại sống tự do phóng khoáng, như là gọi đồ ăn ngoài, vứt đồ lót bữa bãi, ngủ chung giường với Shikimi trước khi nhận ra chuyện đó!?\nDù bị bối rối trước \"gương mặt thật\" của 4 chị em, Shikimi vẫn dần dần giành được lòng tin nhờ khả năng làm việc nhà của mình. Một tin nhắn được gửi đến cậu với nội dung:\n『Lần này, anh cũng sẽ chọn em nhỉ?』 \nDưới mái nhà ấy, vận mệnh của 4 chị em đã xoay chuyển!",
  "author": "Mametaro Yomogi",
  "cover": "https://cdn.discordapp.com/attachments/1502972540316811374/1502972540627456131/33f75ed1-18f3-4c9b-9a63-941d71d6ed97.jpg?ex=6a01a7c1&is=6a005641&hm=cb314d934f239908bff29f705994010be59c3a43d2e56380d0e833447c6ac179",
  "chapters": {
    "1": {
      "title": "",
      "volume": "1",
      "last_updated": "1778429040",
      "groups": {
        "": [
          "https://i.imgur.com/lBtzgcH.jpeg",
          "https://i.imgur.com/t8Pw7R5.jpeg",
          "https://i.imgur.com/8amhC1N.jpeg",
          "https://i.imgur.com/sJCPo4U.jpeg",
          "https://i.imgur.com/YGBV1Va.jpeg",
          "https://i.imgur.com/fKwbwEi.jpeg",
          "https://i.imgur.com/eLKjruq.jpeg",
          "https://i.imgur.com/eJitKkT.jpeg",
          "https://i.imgur.com/HkxjtRs.jpeg",
          "https://i.imgur.com/ZtClP7y.jpeg",
          "https://i.imgur.com/gLWRxQR.jpeg",
          "https://i.imgur.com/E6AuM18.jpeg",
          "https://i.imgur.com/zOPp4gW.jpeg",
          "https://i.imgur.com/0DDS1Os.jpeg",
          "https://i.imgur.com/DJBbzZe.jpeg",
          "https://i.imgur.com/TcEHusu.jpeg",
          "https://i.imgur.com/SUx7Ohy.jpeg",
          "https://i.imgur.com/o7zryYl.jpeg",
          "https://i.imgur.com/JXvQeHV.jpeg",
          "https://i.imgur.com/A6JcZLh.jpeg",
          "https://i.imgur.com/MvCELSh.jpeg",
          "https://i.imgur.com/GUnmLMd.jpeg",
          "https://i.imgur.com/ONCQHhx.jpeg",
          "https://i.imgur.com/6zCTBrJ.jpeg",
          "https://i.imgur.com/rC0cPlI.jpeg",
          "https://i.imgur.com/vTINNZx.jpeg",
          "https://i.imgur.com/XMkTRB4.jpeg",
          "https://i.imgur.com/8vuXbe0.jpeg",
          "https://i.imgur.com/Em9UZtt.jpeg",
          "https://i.imgur.com/BtfQkXO.jpeg",
          "https://i.imgur.com/20S8phF.jpeg"
        ]
      }
    },
    "1.2": {
      "title": "",
      "volume": "1",
      "last_updated": "1778431704",
      "groups": {
        "": [
          "https://i.imgur.com/k23e88O.jpeg",
          "https://i.imgur.com/5xniSP4.jpeg",
          "https://i.imgur.com/tzhIfLx.jpeg",
          "https://i.imgur.com/b7mS050.jpeg",
          "https://i.imgur.com/eCBqTfI.jpeg",
          "https://i.imgur.com/gwAyQdJ.jpeg",
          "https://i.imgur.com/gkxVWQK.jpeg",
          "https://i.imgur.com/tIBKM8y.jpeg",
          "https://i.imgur.com/T00xFJR.jpeg",
          "https://i.imgur.com/dHvX9sO.jpeg",
          "https://i.imgur.com/Skexfbs.jpeg",
          "https://i.imgur.com/GPnoEnt.jpeg",
          "https://i.imgur.com/ORhtLvI.jpeg",
          "https://i.imgur.com/N6yQ94O.jpeg",
          "https://i.imgur.com/kcx35IT.jpeg",
          "https://i.imgur.com/Ypaac8Z.jpeg",
          "https://i.imgur.com/FZcNgQx.jpeg",
          "https://i.imgur.com/5PqApnP.jpeg",
          "https://i.imgur.com/fVzfDgk.jpeg",
          "https://i.imgur.com/B6WGmjL.jpeg",
          "https://i.imgur.com/MLK5yU1.jpeg",
          "https://i.imgur.com/vb4IRHB.jpeg",
          "https://i.imgur.com/cvut0u4.jpeg",
          "https://i.imgur.com/gniFwfZ.jpeg",
          "https://i.imgur.com/p7DkcxS.jpeg",
          "https://i.imgur.com/AShY4um.jpeg",
          "https://i.imgur.com/xXKGLZJ.jpeg",
          "https://i.imgur.com/B2VRK9g.jpeg",
          "https://i.imgur.com/8Ti11p1.jpeg",
          "https://i.imgur.com/sIXkLku.jpeg",
          "https://i.imgur.com/tuUvULp.jpeg",
          "https://i.imgur.com/EkUWSpw.jpeg",
          "https://i.imgur.com/SrEj0W9.jpeg",
          "https://i.imgur.com/JaStwOX.jpeg",
          "https://i.imgur.com/wRhgNxt.jpeg",
          "https://i.imgur.com/RXtFbDH.jpeg",
          "https://i.imgur.com/jslyfeF.jpeg",
          "https://i.imgur.com/hrVotL5.jpeg",
          "https://i.imgur.com/JTxVX3k.jpeg",
          "https://i.imgur.com/bwWarpu.jpeg",
          "https://i.imgur.com/U3R0whG.jpeg",
          "https://i.imgur.com/pFIv1hv.jpeg",
          "https://i.imgur.com/FRN5aEA.jpeg",
          "https://i.imgur.com/qLcEDbx.jpeg"
        ]
      }
    },
    "2": {
      "title": "",
      "volume": "1",
      "last_updated": "1778432266",
      "groups": {
        "": [
          "https://i.imgur.com/wgsgy09.jpeg",
          "https://i.imgur.com/KpdOAK8.jpeg",
          "https://i.imgur.com/6AeyeVE.jpeg",
          "https://i.imgur.com/X5lhjeJ.jpeg",
          "https://i.imgur.com/EMmOgim.jpeg",
          "https://i.imgur.com/oz6I7NI.jpeg",
          "https://i.imgur.com/lE0DDVD.jpeg",
          "https://i.imgur.com/N92i7sP.jpeg",
          "https://i.imgur.com/ozAiNwW.jpeg",
          "https://i.imgur.com/ULAnKmN.jpeg",
          "https://i.imgur.com/Wt2857G.jpeg",
          "https://i.imgur.com/J8miE6y.jpeg",
          "https://i.imgur.com/2qvGDlN.jpeg",
          "https://i.imgur.com/Y6WqTtO.jpeg",
          "https://i.imgur.com/Cwa0qno.jpeg",
          "https://i.imgur.com/UiAQLqP.jpeg",
          "https://i.imgur.com/zylVXUa.jpeg",
          "https://i.imgur.com/5pHdEH8.jpeg",
          "https://i.imgur.com/zqmFaUZ.jpeg",
          "https://i.imgur.com/2Q648ME.jpeg",
          "https://i.imgur.com/wiFVylk.jpeg",
          "https://i.imgur.com/GmhTEmb.jpeg",
          "https://i.imgur.com/9emQ2rF.jpeg",
          "https://i.imgur.com/Tc3okLD.jpeg",
          "https://i.imgur.com/3UDYRzU.jpeg",
          "https://i.imgur.com/LK2tx6T.jpeg",
          "https://i.imgur.com/K31htxB.jpeg",
          "https://i.imgur.com/TbezrkN.jpeg",
          "https://i.imgur.com/d1DOp3b.jpeg",
          "https://i.imgur.com/pH6Ob4a.jpeg",
          "https://i.imgur.com/y43yvYJ.jpeg",
          "https://i.imgur.com/5CoX1eF.jpeg",
          "https://i.imgur.com/rdLEijO.jpeg",
          "https://i.imgur.com/WzVGYk6.jpeg",
          "https://i.imgur.com/OhSVIUB.jpeg",
          "https://i.imgur.com/pJpCtC2.jpeg",
          "https://i.imgur.com/brGWiDM.jpeg",
          "https://i.imgur.com/uA9LIPs.jpeg",
          "https://i.imgur.com/51e5Tij.jpeg",
          "https://i.imgur.com/ctidg9s.jpeg",
          "https://i.imgur.com/SRNVscY.jpeg",
          "https://i.imgur.com/n2TOlSd.jpeg",
          "https://i.imgur.com/wxZl0zT.jpeg",
          "https://i.imgur.com/jjiaHsC.jpeg",
          "https://i.imgur.com/mXOf5IL.jpeg"
        ]
      }
    }
  },
  "artist": "Mametaro Yomogi"
}
